/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anasayfa;

import bean.KayitOlanKullaniciBilgileri;
import bean.TarihCevir;
import dbislemleri.DatabaseIslemleri;
import java.text.ParseException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import liste.Demirbas;
import liste.Personel;
import login.Login;
import utils.HibernateUtil;

/**
 *
 * @author mert tan
 */
public class Anasayfa extends javax.swing.JFrame {
	
	private KayitOlanKullaniciBilgileri kullanici;
	private Login login;
        private DatabaseIslemleri db = new DatabaseIslemleri();


	public Anasayfa(KayitOlanKullaniciBilgileri kullanici, Login login) {
                this.kullanici = kullanici;
		this.login = login;
		initComponents();
		initAllTab();
                demirbaslariListele();
                String[] aramaKriterleri = {"Ürün Koduna Göre","Ürün Adına Göre"};
    
                cmb_Zimmetli.setModel(new DefaultComboBoxModel(db.butunKayitliPersonelleriGetir().toArray()));
                cmb_FiltreTipi.setModel(new DefaultComboBoxModel(aramaKriterleri));
                
                cmb_ZimmetliGuncelle.setModel(new DefaultComboBoxModel(db.butunKayitliPersonelleriGetir().toArray()));
                kullaniciProfiliDoldur();
		
	}

	public void initAllTab() {

	}
        public void demirbaslariListedenSil(){
            DefaultTableModel model = (DefaultTableModel) tbl_DemirbasListesi.getModel();
            int rowCount = model.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                model.removeRow(i);
            }
        }
        public void demirbaslariListele()
        {
//            demirbaslariListedenSil();
            DefaultTableModel model = (DefaultTableModel) tbl_DemirbasListesi.getModel();
            
            List<Demirbas> list = new ArrayList<>();
            for(model.Demirbas demirbasModel : db.butunDemirbaslariGetir()){
                Demirbas demirbas = demirbasModelCevir(demirbasModel);
                list.add(demirbas);
            } 
            Object rowData[] = new Object[4];
            for(int i = 0; i < list.size(); i++)
            {
                rowData[0] = list.get(i).getUrunKodu();
                rowData[1] = list.get(i).getUrunAdi();
                rowData[2] = list.get(i).getUrunKategorisi();
                rowData[3] = TarihCevir.convertStringToDate(list.get(i).getKayitTarihi());
                model.addRow(rowData);
            }       
            
        }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTab = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_UrunKodu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_UrunAdi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_UrunKategori = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_DemirbasKayitKaydet = new javax.swing.JButton();
        btn_DemirbasKayitTemizle = new javax.swing.JButton();
        cmb_Zimmetli = new javax.swing.JComboBox<String>();
        txt_Adet = new javax.swing.JFormattedTextField();
        txt_KayitTarihi = new javax.swing.JFormattedTextField();
        txt_BirimFiyati = new javax.swing.JFormattedTextField();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        cmb_FiltreTipi = new javax.swing.JComboBox<String>();
        jLabel16 = new javax.swing.JLabel();
        btn_DemirbasDetayliAra = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txt_DemirbasDetayliAra = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_DemirbasDetayliAraUrunKodu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_DemirbasDetayliAraUrunAdi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_DemirbasDetayliAraBirimFiyati = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_DemirbasDetayliAraAdet = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_DemirbasDetayliAraKayitTarihi = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_DemirbasDetayliAraUrunKategori = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_DemirbasDetayliAraZimmetli = new javax.swing.JTextField();
        btn_DemirbasDetayliAraSil = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txt_UrunKoduGuncelle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_UrunAdiGuncelle = new javax.swing.JTextField();
        txt_BirimFiyatiGuncelle = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_AdetGuncelle = new javax.swing.JTextField();
        txt_KayitTarihiGuncelle = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_UrunKategoriGuncelle = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmb_ZimmetliGuncelle = new javax.swing.JComboBox<String>();
        btn_DemirbasGuncelleKaydet = new javax.swing.JButton();
        btn_DemirbasGuncelleTemizle = new javax.swing.JButton();
        btn_DemirbasGuncelleBul = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        javax.swing.JLabel lblAdi = new javax.swing.JLabel();
        txt_KullaniciProfilAdi = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_KullaniciProfilSoyadi = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_KullaniciProfilKullaniciAdi = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_KullaniciProfilMailAdresi = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btn_KullaniciProfilKaydet = new javax.swing.JButton();
        txt_KullaniciProfilParola = new javax.swing.JPasswordField();
        txt_KullaniciProfilTel = new javax.swing.JFormattedTextField();
        btn_Logout = new javax.swing.JButton();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txt_PersonelKodu = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_PersonelAdi = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txt_PersonelMaili = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_PersonelGorevi = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_PersonelSoyadi = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txt_PersonelDepartmani = new javax.swing.JTextField();
        txt_PersonelKaydet = new javax.swing.JButton();
        txt_PersonelTemiz = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_demirbasSil = new javax.swing.JButton();
        txt_DemirbasSilUrunKodu = new javax.swing.JTextField();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_DemirbasListesi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DEMİRBAŞ TAKİP PROGRAMI");

        jLabel1.setText("Ürün Kodu");

        jLabel2.setText("Ürün Adı");

        jLabel3.setText("Birim Fiyatı");

        jLabel4.setText("Adet");

        jLabel5.setText("Alış Tarihi");

        jLabel6.setText("Ürün Kategori");

        jLabel7.setText("Zimmetlisi");

        btn_DemirbasKayitKaydet.setText("KAYDET");
        btn_DemirbasKayitKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DemirbasKayitKaydetActionPerformed(evt);
            }
        });

        btn_DemirbasKayitTemizle.setText("TEMIZLE");
        btn_DemirbasKayitTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DemirbasKayitTemizleActionPerformed(evt);
            }
        });

        cmb_Zimmetli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_Adet.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        txt_KayitTarihi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        txt_KayitTarihi.setToolTipText("Formatı dd-MM-yyyy şeklinde giriniz..");

        txt_BirimFiyati.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_KayitTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_DemirbasKayitKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btn_DemirbasKayitTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE))
                                    .addComponent(txt_UrunKategori)
                                    .addComponent(cmb_Zimmetli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txt_Adet, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_UrunAdi)
                            .addComponent(txt_UrunKodu)
                            .addComponent(txt_BirimFiyati, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_UrunKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_UrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_BirimFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Adet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_KayitTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_UrunKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Zimmetli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DemirbasKayitKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DemirbasKayitTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jTabbedPane2.addTab("YENİ KAYIT", jPanel1);

        mainTab.addTab("YENİ DEMİRAŞ KAYIT FORMU", jTabbedPane2);

        cmb_FiltreTipi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Filtre Tipi");

        btn_DemirbasDetayliAra.setText("ARA");
        btn_DemirbasDetayliAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DemirbasDetayliAraActionPerformed(evt);
            }
        });

        jLabel17.setText("Ürün Kodu");

        txt_DemirbasDetayliAraUrunKodu.setEnabled(false);

        jLabel18.setText("Ürün Adı");

        txt_DemirbasDetayliAraUrunAdi.setEnabled(false);

        jLabel19.setText("Birim Fiyatı");

        txt_DemirbasDetayliAraBirimFiyati.setEnabled(false);

        jLabel20.setText("Adet");

        txt_DemirbasDetayliAraAdet.setEnabled(false);

        jLabel21.setText("AlışTarihi");

        txt_DemirbasDetayliAraKayitTarihi.setEnabled(false);

        jLabel22.setText("Ürün Kategori");

        txt_DemirbasDetayliAraUrunKategori.setEnabled(false);

        jLabel23.setText("Zimmetlisi");

        txt_DemirbasDetayliAraZimmetli.setEnabled(false);

        btn_DemirbasDetayliAraSil.setText("SİL");
        btn_DemirbasDetayliAraSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DemirbasDetayliAraSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(36, 36, 36)
                        .addComponent(cmb_FiltreTipi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_DemirbasDetayliAra, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_DemirbasDetayliAra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(31, 31, 31)
                            .addComponent(txt_DemirbasDetayliAraUrunKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_DemirbasDetayliAraAdet)
                                        .addComponent(txt_DemirbasDetayliAraKayitTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_DemirbasDetayliAraZimmetli, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_DemirbasDetayliAraUrunKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_DemirbasDetayliAraUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_DemirbasDetayliAraBirimFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_DemirbasDetayliAraSil, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_FiltreTipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btn_DemirbasDetayliAra)
                    .addComponent(txt_DemirbasDetayliAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DemirbasDetayliAraSil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_DemirbasDetayliAraUrunKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_DemirbasDetayliAraUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DemirbasDetayliAraBirimFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DemirbasDetayliAraAdet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DemirbasDetayliAraKayitTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DemirbasDetayliAraUrunKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txt_DemirbasDetayliAraZimmetli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("DETAYLI ARAMA", jPanel4);

        mainTab.addTab("DEMİRMAŞ DETAYLI ARA", jTabbedPane3);

        jLabel9.setText("Ürün Kodu");

        jLabel10.setText("Ürün Adı");

        jLabel11.setText("Birim Fiyatı");

        jLabel12.setText("Adet");

        txt_KayitTarihiGuncelle.setToolTipText("Formatı dd-MM-yyyy şeklinde giriniz..");
        txt_KayitTarihiGuncelle.setEnabled(false);

        jLabel13.setText("Alış Tarihi");

        jLabel14.setText("Ürün Kategori");

        jLabel15.setText("Zimmetlisi");

        cmb_ZimmetliGuncelle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_DemirbasGuncelleKaydet.setText("KAYDET");
        btn_DemirbasGuncelleKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DemirbasGuncelleKaydetActionPerformed(evt);
            }
        });

        btn_DemirbasGuncelleTemizle.setText("TEMIZLE");
        btn_DemirbasGuncelleTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DemirbasGuncelleTemizleActionPerformed(evt);
            }
        });

        btn_DemirbasGuncelleBul.setText("BUL");
        btn_DemirbasGuncelleBul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DemirbasGuncelleBulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(34, 34, 34)
                        .addComponent(txt_UrunKoduGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_DemirbasGuncelleBul))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_KayitTarihiGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(txt_AdetGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_UrunKategoriGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(btn_DemirbasGuncelleKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_DemirbasGuncelleTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmb_ZimmetliGuncelle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_UrunAdiGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                .addComponent(txt_BirimFiyatiGuncelle)))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_UrunKoduGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DemirbasGuncelleBul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_UrunAdiGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_BirimFiyatiGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_AdetGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_KayitTarihiGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_UrunKategoriGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmb_ZimmetliGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DemirbasGuncelleKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DemirbasGuncelleTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        jTabbedPane5.addTab("GÜNCELLE", jPanel3);

        mainTab.addTab("DEMİRBAŞ BİLGİ GÜNCLLE", jTabbedPane5);

        lblAdi.setText("Adı");

        txt_KullaniciProfilAdi.setEditable(false);

        jLabel25.setText("Soyadı");

        txt_KullaniciProfilSoyadi.setEditable(false);

        jLabel27.setText("Kullanıcı Adı");

        txt_KullaniciProfilKullaniciAdi.setEditable(false);

        jLabel28.setText("Parolası");

        jLabel29.setText("Mail Adresi");

        txt_KullaniciProfilMailAdresi.setEditable(false);

        jLabel30.setText("Tel");

        btn_KullaniciProfilKaydet.setText("KAYDET");
        btn_KullaniciProfilKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KullaniciProfilKaydetActionPerformed(evt);
            }
        });

        txt_KullaniciProfilParola.setEditable(false);

        try {
            txt_KullaniciProfilTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btn_Logout.setText("GÜVENLİ ÇIKIŞ");
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_KullaniciProfilSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblAdi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_KullaniciProfilAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_KullaniciProfilKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_Logout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_KullaniciProfilKaydet))
                            .addComponent(txt_KullaniciProfilParola, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(txt_KullaniciProfilMailAdresi, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(txt_KullaniciProfilTel))))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdi)
                    .addComponent(txt_KullaniciProfilAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txt_KullaniciProfilSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_KullaniciProfilKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_KullaniciProfilParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_KullaniciProfilMailAdresi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(txt_KullaniciProfilTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_KullaniciProfilKaydet)
                    .addComponent(btn_Logout))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Kullanıcı", jPanel5);

        jTabbedPane6.addTab("KULLANICI PROFİLİ", jTabbedPane7);

        jLabel24.setText("PERSONEL KODU");

        jLabel26.setText("PERSONEL ADI");

        jLabel31.setText("PERSONEL MAİLİ");

        jLabel32.setText("PERSONEL GÖREVİ");

        jLabel33.setText("PERSONEL SOYADI");

        jLabel34.setText("PERSONEL DEPARTMANI");

        txt_PersonelKaydet.setText("KAYDET");
        txt_PersonelKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PersonelKaydetActionPerformed(evt);
            }
        });

        txt_PersonelTemiz.setText("TEMİZLE");
        txt_PersonelTemiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PersonelTemizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txt_PersonelTemiz)
                        .addGap(18, 18, 18)
                        .addComponent(txt_PersonelKaydet))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_PersonelAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_PersonelKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_PersonelSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_PersonelDepartmani, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_PersonelGorevi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_PersonelMaili, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_PersonelKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_PersonelAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_PersonelSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txt_PersonelDepartmani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txt_PersonelGorevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txt_PersonelMaili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_PersonelKaydet)
                    .addComponent(txt_PersonelTemiz))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("PERSONEL İŞLEMLER", jPanel6);

        jTabbedPane6.addTab("PERSONEL İŞLEMLERİ", jTabbedPane8);

        mainTab.addTab("DİĞER", jTabbedPane6);

        jLabel8.setText("Ürün Kodu");

        btn_demirbasSil.setText("SİL");
        btn_demirbasSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_demirbasSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_demirbasSil, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_DemirbasSilUrunKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_DemirbasSilUrunKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btn_demirbasSil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("SİL", jPanel2);

        mainTab.addTab("DEMİRBAŞ SİL", jTabbedPane4);

        tbl_DemirbasListesi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün Kodu", "Ürün Adı", "Ürün Kategorisi", "Kayıt Tarihi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_DemirbasListesi);

        jTabbedPane9.addTab("DEMİRBAŞ LİSTE", jScrollPane3);

        mainTab.addTab("DEMİRBAŞ LİSTESİ", jTabbedPane9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DemirbasKayitTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DemirbasKayitTemizleActionPerformed
    temizle(txt_Adet,txt_BirimFiyati,txt_KayitTarihi,txt_UrunAdi,txt_UrunKategori,txt_UrunKodu);
    cmb_Zimmetli.addItem("seçiniz");
    }//GEN-LAST:event_btn_DemirbasKayitTemizleActionPerformed
    private void temizle(JTextField textField1,JTextField textField2,JTextField textField3,JTextField textField4,
            JTextField textField5,JTextField textField6){
        textField1.setText("");
        textField2.setText("");
        textField3.setText("");
        textField4.setText("");
        textField5.setText("");
        textField6.setText("");
    }
    private void btn_DemirbasGuncelleKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DemirbasGuncelleKaydetActionPerformed
        if(!(textFieldKontroluYap(txt_BirimFiyatiGuncelle)|| textFieldKontroluYap(txt_AdetGuncelle)||
                textFieldKontroluYap(txt_UrunAdiGuncelle)|| textFieldKontroluYap(txt_UrunKategoriGuncelle))){
           
            Demirbas guncellenecekDemirbas = demirbasGetir(txt_UrunKoduGuncelle);
            guncellenecekDemirbas.setAdet(Integer.valueOf(txt_AdetGuncelle.getText()));
            guncellenecekDemirbas.setBirimFiyati(Double.valueOf(txt_BirimFiyatiGuncelle.getText()));
            guncellenecekDemirbas.setUrunAdi(txt_UrunAdiGuncelle.getText());
            guncellenecekDemirbas.setUrunKategorisi(txt_UrunKategoriGuncelle.getText());
            
            model.Demirbas modelDemirbas = demirbasFormCevir(guncellenecekDemirbas);
            

            /*modelDemirbas.setTeslimTarihi(LocalDateTime.now());
            ;
            modelDemirbas.setTeslimEden(db.personelGetirMailAdresineGore(kullanici.getMail()));
            modelDemirbas.setTeslimAlan((model.Calisan)cmb_ZimmetliGuncelle.getSelectedItem());
            */
            db.demirbasGuncelle(modelDemirbas);
            
            JOptionPane.showMessageDialog(rootPane, "Demirbaş Güncellendi", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
            demirbaslariListedenSil();
            demirbaslariListele();
            
        }else{
            
            JOptionPane.showMessageDialog(rootPane, "Hatalı Bilgi Girişi", "Failure", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btn_DemirbasGuncelleKaydetActionPerformed

    private void btn_DemirbasGuncelleTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DemirbasGuncelleTemizleActionPerformed
        temizle(txt_AdetGuncelle,txt_BirimFiyatiGuncelle,txt_KayitTarihiGuncelle,txt_UrunAdiGuncelle,txt_UrunKategoriGuncelle,txt_UrunKoduGuncelle);
        cmb_ZimmetliGuncelle.addItem("seçiniz");
    }//GEN-LAST:event_btn_DemirbasGuncelleTemizleActionPerformed

    private void btn_DemirbasDetayliAraSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DemirbasDetayliAraSilActionPerformed
        temizle(txt_DemirbasDetayliAra,txt_DemirbasDetayliAraAdet,txt_DemirbasDetayliAraBirimFiyati,txt_DemirbasDetayliAraKayitTarihi,
                txt_DemirbasDetayliAraUrunAdi,txt_DemirbasDetayliAraUrunKategori);
        
        txt_DemirbasDetayliAraUrunKodu.setText("");
        txt_DemirbasDetayliAraZimmetli.setText("");
    }//GEN-LAST:event_btn_DemirbasDetayliAraSilActionPerformed

    private void btn_DemirbasGuncelleBulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DemirbasGuncelleBulActionPerformed
        if(!textFieldKontroluYap(txt_UrunKoduGuncelle)){
            
            Demirbas demirbas = demirbasGetir(txt_UrunKoduGuncelle); 
            if(demirbas!=null) guncelleEkraniniDoldur(demirbas);
            else JOptionPane.showMessageDialog(rootPane, "Demirbaş Bulunamadı", "Failure", JOptionPane.ERROR_MESSAGE);
        }else{
           JOptionPane.showMessageDialog(rootPane, "Demirbaş Bulunamadı", "Failure", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btn_DemirbasGuncelleBulActionPerformed
    private void guncelleEkraniniDoldur(Demirbas demirbas){
        temizle(txt_KayitTarihiGuncelle,txt_UrunAdiGuncelle,txt_UrunKategoriGuncelle,txt_UrunKoduGuncelle,txt_BirimFiyatiGuncelle,txt_AdetGuncelle);
        
        txt_AdetGuncelle.setText(String.valueOf(demirbas.getAdet()));
        txt_BirimFiyatiGuncelle.setText(""+demirbas.getBirimFiyati());
        txt_KayitTarihiGuncelle.setText(TarihCevir.convertStringToDate(demirbas.getKayitTarihi()));
        txt_UrunAdiGuncelle.setText(demirbas.getUrunAdi());
        txt_UrunKategoriGuncelle.setText(demirbas.getUrunKategorisi());
        txt_UrunKoduGuncelle.setText(demirbas.getUrunKodu());
        cmb_ZimmetliGuncelle.setSelectedItem(demirbas.getTeslimAlan());
    }
    private void btn_DemirbasDetayliAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DemirbasDetayliAraActionPerformed
        if(textFieldKontroluYap(txt_DemirbasDetayliAra)){
            JOptionPane.showMessageDialog(rootPane, "Demirbaş Bulunamadı", "Failure", JOptionPane.ERROR_MESSAGE);
            return;
        }
        demirbasAra();
    }//GEN-LAST:event_btn_DemirbasDetayliAraActionPerformed

    private void btn_demirbasSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_demirbasSilActionPerformed
        if(textFieldKontroluYap(txt_DemirbasSilUrunKodu)){
            JOptionPane.showMessageDialog(rootPane, "Demirbaş Bulunamadı", "Failure", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int silmeSorusununCevabi = JOptionPane.showConfirmDialog(rootPane, txt_DemirbasSilUrunKodu.getText() + " Kodlu Demirbaşı Silmek İstiyor musunuz ? ", "Soru", JOptionPane.YES_NO_OPTION);
        if (silmeSorusununCevabi == JOptionPane.YES_OPTION) {            

            List<model.Demirbas> demirbaslar  = db.butunDemirbaslariGetir();
            List<Demirbas> demirbasFormListe = new ArrayList<>();
            for(model.Demirbas demirbas: demirbaslar){
                demirbasFormListe.add(demirbasModelCevir(demirbas));
            }
            ListIterator<Demirbas> arananDemirbas = demirbasFormListe.listIterator();
            while(arananDemirbas.hasNext()){
                if(arananDemirbas.next().getUrunKodu().equals(txt_DemirbasSilUrunKodu.getText().trim())){
                    arananDemirbas.remove();
                    db.demirbasSil(db.demirbasiUrunKodunaGoreGetir(txt_DemirbasSilUrunKodu.getText().trim()));

                }
            }


            JOptionPane.showMessageDialog(rootPane, txt_DemirbasSilUrunKodu.getText() +" Kodlu Demirbaş Silindi", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
            txt_DemirbasSilUrunKodu.setText("");
            demirbaslariListedenSil();
            demirbaslariListele();

       } 
    }//GEN-LAST:event_btn_demirbasSilActionPerformed

    private void txt_PersonelKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PersonelKaydetActionPerformed
        
        if((textFieldKontroluYap(txt_PersonelKodu)|| textFieldKontroluYap(txt_PersonelAdi)||
        textFieldKontroluYap(txt_PersonelSoyadi)|| textFieldKontroluYap(txt_PersonelDepartmani)||
        textFieldKontroluYap(txt_PersonelGorevi) || textFieldKontroluYap(txt_PersonelMaili))){
            JOptionPane.showMessageDialog(rootPane, "Giriş bilgileri hatalı", "Failure", JOptionPane.ERROR_MESSAGE);
            return ;
        }
            
        if(TarihCevir.mailAdresKontroluYap(txt_PersonelMaili.getText())){
            JOptionPane.showMessageDialog(rootPane, "Email formatı hatalı", "Failure", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        
        Personel yeniPersonel = new Personel();   
        yeniPersonel.setPersonelAdi(txt_PersonelAdi.getText().trim()); 
        yeniPersonel.setPersonelDepartmani(txt_PersonelDepartmani.getText().trim());
        yeniPersonel.setPersonelGorevi(txt_PersonelGorevi.getText().trim());
        yeniPersonel.setPersonelKodu(txt_PersonelKodu.getText().trim());
        yeniPersonel.setPersonelMail(txt_PersonelMaili.getText().trim());
        yeniPersonel.setPersonelSoyadi(txt_PersonelSoyadi.getText().trim());
            
        model.Calisan calisan = db.personelBulMaileGore(yeniPersonel.getPersonelMail());
        if(calisan!=null){
            JOptionPane.showMessageDialog(rootPane, "Sistemde personel mevcut", "Failure", JOptionPane.ERROR_MESSAGE);                    
            return ;
        }
        
        db.personelKaydet(calisanPersonelCevir(yeniPersonel));
        cmb_Zimmetli.setModel(new DefaultComboBoxModel(db.butunPersonelleriGetir().toArray()));   
        cmb_ZimmetliGuncelle.setModel(new DefaultComboBoxModel(db.butunPersonelleriGetir().toArray()));
        
            
        JOptionPane.showMessageDialog(rootPane, "Personel başarılı kaydedildi", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_txt_PersonelKaydetActionPerformed
    private model.Calisan calisanPersonelCevir(Personel personel){
        if(personel==null) return null;
        
        model.Calisan calisan = new model.Calisan();
        calisan.setKayitTarihi(LocalDateTime.now());
        calisan.setPersonelAdi(personel.getPersonelAdi());
        calisan.setPersonelDepartmani(personel.getPersonelDepartmani());
        calisan.setPersonelGorevi(personel.getPersonelGorevi());
        calisan.setPersonelKodu(personel.getPersonelKodu());
        calisan.setPersonelMail(personel.getPersonelMail());
        calisan.setPersonelSoyadi(personel.getPersonelSoyadi());
        
        return calisan;
    }
    
    private Personel personelCalisanCevir(model.Calisan calisan){
        if(calisan==null) return null;
        
        Personel personel = new Personel();
        calisan = HibernateUtil.buildSessionFactory().load(model.Calisan.class, calisan.getId());
        personel.setKayitTarihi(calisan.getKayitTarihi());
        personel.setPersonelAdi(calisan.getPersonelAdi());
        personel.setPersonelDepartmani(calisan.getPersonelDepartmani());
        personel.setPersonelGorevi(calisan.getPersonelGorevi());
        personel.setPersonelKodu(calisan.getPersonelKodu());
        personel.setPersonelMail(calisan.getPersonelMail());
        personel.setPersonelSoyadi(calisan.getPersonelSoyadi());
        
        return personel;
    }
    private void txt_PersonelTemizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PersonelTemizActionPerformed
        temizle(txt_PersonelAdi,txt_PersonelDepartmani,txt_PersonelGorevi,txt_PersonelKodu,txt_PersonelMaili,txt_PersonelSoyadi);
    }//GEN-LAST:event_txt_PersonelTemizActionPerformed
    
    private void kullaniciProfiliDoldur(){
    txt_KullaniciProfilAdi.setText(kullanici.getAdi());
    txt_KullaniciProfilKullaniciAdi.setText(kullanici.getKullaniciAdi());
    txt_KullaniciProfilMailAdresi.setText(kullanici.getMail());
    txt_KullaniciProfilParola.setText(kullanici.getParola().toString());
    txt_KullaniciProfilSoyadi.setText(kullanici.getSoyadi());
    txt_KullaniciProfilTel.setText(kullanici.getTelefonNumarasi());
    }    
    private void btn_KullaniciProfilKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KullaniciProfilKaydetActionPerformed
        if(!textFieldKontroluYap(txt_KullaniciProfilTel)){
            kullanici.setTelefonNumarasi(txt_KullaniciProfilTel.getText());
            JOptionPane.showMessageDialog(rootPane, "Girilen Telefon Bilgisi Kaydedildi", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Girilen Telefon Bilgisi Hatalı", "Failure", JOptionPane.ERROR_MESSAGE);                    

        }    
    }//GEN-LAST:event_btn_KullaniciProfilKaydetActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        this.dispose();
        login.setVisible(true);
        
    }//GEN-LAST:event_btn_LogoutActionPerformed
    private void demirbasAra(){
        int secilenAramaTipi = cmb_FiltreTipi.getSelectedIndex();
        boolean demirbasBulundumu=false;
        if(secilenAramaTipi==0){
            
            model.Demirbas arananDemirbas = db.demirbasiUrunKodunaGoreGetir(txt_DemirbasDetayliAra.getText());
            
            if(arananDemirbas!= null ){
                Demirbas demirbas = demirbasModelCevir(arananDemirbas);
                aramaEkraniniDoldur(demirbas);
                demirbasBulundumu = true;
            }
            
        }else if(secilenAramaTipi==1){
            model.Demirbas arananDemirbas = db.demirbasiUrunAdinaGoreGetir(txt_DemirbasDetayliAra.getText());
            if(arananDemirbas != null ){
                Demirbas demirbas = demirbasModelCevir(arananDemirbas);
                aramaEkraniniDoldur(demirbas);
                demirbasBulundumu = true;   
            }
        }
        if(demirbasBulundumu==false){
            JOptionPane.showMessageDialog(rootPane, "Aranan Demirbaş Bulunamadı", "Bulunamadı", JOptionPane.ERROR_MESSAGE);                    
        }
    }
    
    private void aramaEkraniniDoldur(Demirbas demirbas){
        
        temizle(txt_DemirbasDetayliAraAdet,txt_DemirbasDetayliAraBirimFiyati,txt_DemirbasDetayliAraKayitTarihi,txt_DemirbasDetayliAraUrunAdi
                ,txt_DemirbasDetayliAraUrunKategori,txt_DemirbasDetayliAraUrunKodu);
        txt_DemirbasDetayliAraZimmetli.setText("");
        
        txt_DemirbasDetayliAraAdet.setText(String.valueOf(demirbas.getAdet()));
        txt_DemirbasDetayliAraBirimFiyati.setText(""+demirbas.getBirimFiyati());
        txt_DemirbasDetayliAraKayitTarihi.setText(TarihCevir.convertStringToDate(demirbas.getKayitTarihi()));
        txt_DemirbasDetayliAraUrunAdi.setText(demirbas.getUrunAdi());
        txt_DemirbasDetayliAraUrunKategori.setText(demirbas.getUrunKategorisi());
        txt_DemirbasDetayliAraUrunKodu.setText(demirbas.getUrunKodu());
        
        
        txt_DemirbasDetayliAraZimmetli.setText(demirbas.getTeslimAlan().getPersonelAdi()+ "  " + demirbas.getTeslimAlan().getPersonelSoyadi());
    }
    


    private boolean textFieldKontroluYap(JTextField textField){
        return (textField.getText().isEmpty());

    }
    private boolean kontrolEtDemirbasKayitBilgileri(){
        return (textFieldKontroluYap(txt_UrunKodu)||
        textFieldKontroluYap(txt_UrunAdi)||
        textFieldKontroluYap(txt_BirimFiyati)||
        textFieldKontroluYap(txt_Adet)||
        textFieldKontroluYap(txt_KayitTarihi)|| 
        demirbasVarmi(txt_UrunKodu));
    }
    private boolean demirbasVarmi(JTextField textField){
       return db.demirbasiUrunKodunaGoreGetir(textField.getText().trim()) == null ?  false : true;
    }
    
     private Demirbas demirbasGetir(JTextField textField){
        return demirbasModelCevir(db.demirbasiUrunKodunaGoreGetir(textField.getText().trim()));
     }
    private Demirbas demirbasModelCevir(model.Demirbas demirbas){
        if(demirbas==null) return null;
        Demirbas demirbasForm = new Demirbas();
        demirbasForm.setAdet(demirbas.getAdet());
        demirbasForm.setBirimFiyati(demirbas.getBirimFiyati());
        demirbasForm.setKayitTarihi(demirbas.getKayitTarihi());
        demirbasForm.setUrunAdi(demirbas.getUrunAdi());
        demirbasForm.setUrunKategorisi(demirbas.getUrunKategorisi());
        demirbasForm.setUrunKodu(demirbas.getUrunKodu());
        demirbasForm.setTeslimTarihi(demirbas.getTeslimTarihi());
        demirbasForm.setTeslimAlan(personelCalisanCevir(demirbas.getTeslimAlan()));
        demirbasForm.setTeslimEden(personelCalisanCevir(demirbas.getTeslimEden()));
        return demirbasForm;
    }
    
    private model.Demirbas demirbasFormCevir(Demirbas demirbas){
        if(demirbas==null) return null;
        model.Demirbas demirbasModel = new model.Demirbas();
        demirbasModel.setAdet(demirbas.getAdet());
        demirbasModel.setBirimFiyati(demirbas.getBirimFiyati());
        demirbasModel.setKayitTarihi(demirbas.getKayitTarihi());
        demirbasModel.setUrunAdi(demirbas.getUrunAdi());
        demirbasModel.setUrunKategorisi(demirbas.getUrunKategorisi());
        demirbasModel.setUrunKodu(demirbas.getUrunKodu());
        demirbasModel.setTeslimTarihi(demirbas.getTeslimTarihi());
        demirbasModel.setTeslimAlan(calisanPersonelCevir(demirbas.getTeslimAlan()));
        demirbasModel.setTeslimEden(calisanPersonelCevir(demirbas.getTeslimEden()));
        
        return demirbasModel;
    }
        
    private void btn_DemirbasKayitKaydetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_DemirbasKayitKaydetActionPerformed
        if(!kontrolEtDemirbasKayitBilgileri()){
            try{
                demirbasKayitOlustur();
                demirbaslariListedenSil();
                demirbaslariListele();
                
                JOptionPane.showMessageDialog(rootPane, "Kayıt Ekleme Başarılı. ");
                 temizle(txt_Adet,txt_BirimFiyati,txt_KayitTarihi,txt_UrunAdi,txt_UrunKategori,txt_UrunKodu);
    cmb_Zimmetli.addItem("seçiniz");
        
            }catch(ParseException p){
                JOptionPane.showMessageDialog(rootPane, "Hatalı Tarih Formatı Girişi Yapıldı.");
            }
          
        }else{
            JOptionPane.showMessageDialog(rootPane, "Demirbaş Girişinde Bilgi Eksikliği Yapıldı. Ya da girilen demirbaş sistemde mevcut.");
            return ;
                    
        }
    }
    

    private Demirbas demirbasKayitOlustur() throws ParseException {
        Demirbas demirbas = new Demirbas();
        
        demirbas.setUrunKodu(txt_UrunKodu.getText());
        demirbas.setUrunAdi(txt_UrunAdi.getText());
        demirbas.setBirimFiyati(Double.valueOf(txt_BirimFiyati.getText()));
        demirbas.setAdet(Integer.valueOf(txt_Adet.getText()));
        System.out.println(txt_KayitTarihi.getText());
        demirbas.setKayitTarihi(TarihCevir.tarihCevir(txt_KayitTarihi.getText()));
        demirbas.setUrunKategorisi(txt_UrunKategori.getText());
     
        model.Demirbas modelDemirbas = demirbasFormCevir(demirbas);
        modelDemirbas.setTeslimAlan(((model.Calisan)cmb_Zimmetli.getSelectedItem()));
        modelDemirbas.setTeslimTarihi(LocalDateTime.now());
        modelDemirbas.setTeslimEden(calisanPersonelCevir(loginOlanKullaniciTeslimEdenPersonelBul()));
        
        db.demirbasKaydet(modelDemirbas);
        
        return demirbas;
                
    }

    private Personel loginOlanKullaniciTeslimEdenPersonelBul(){
        
        Personel p = personelCalisanCevir(db.personelGetirMailAdresineGore(kullanici.getMail()));
       
        if(p != null ){
            return p;
        }
       
        return null;
    }
	/**
	 * @param args the command line arguments
	 */
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DemirbasDetayliAra;
    private javax.swing.JButton btn_DemirbasDetayliAraSil;
    private javax.swing.JButton btn_DemirbasGuncelleBul;
    private javax.swing.JButton btn_DemirbasGuncelleKaydet;
    private javax.swing.JButton btn_DemirbasGuncelleTemizle;
    private javax.swing.JButton btn_DemirbasKayitKaydet;
    private javax.swing.JButton btn_DemirbasKayitTemizle;
    private javax.swing.JButton btn_KullaniciProfilKaydet;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_demirbasSil;
    private javax.swing.JComboBox<String> cmb_FiltreTipi;
    private javax.swing.JComboBox<String> cmb_Zimmetli;
    private javax.swing.JComboBox<String> cmb_ZimmetliGuncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JTable tbl_DemirbasListesi;
    private javax.swing.JFormattedTextField txt_Adet;
    private javax.swing.JTextField txt_AdetGuncelle;
    private javax.swing.JFormattedTextField txt_BirimFiyati;
    private javax.swing.JTextField txt_BirimFiyatiGuncelle;
    private javax.swing.JTextField txt_DemirbasDetayliAra;
    private javax.swing.JTextField txt_DemirbasDetayliAraAdet;
    private javax.swing.JTextField txt_DemirbasDetayliAraBirimFiyati;
    private javax.swing.JTextField txt_DemirbasDetayliAraKayitTarihi;
    private javax.swing.JTextField txt_DemirbasDetayliAraUrunAdi;
    private javax.swing.JTextField txt_DemirbasDetayliAraUrunKategori;
    private javax.swing.JTextField txt_DemirbasDetayliAraUrunKodu;
    private javax.swing.JTextField txt_DemirbasDetayliAraZimmetli;
    private javax.swing.JTextField txt_DemirbasSilUrunKodu;
    private javax.swing.JFormattedTextField txt_KayitTarihi;
    private javax.swing.JTextField txt_KayitTarihiGuncelle;
    private javax.swing.JTextField txt_KullaniciProfilAdi;
    private javax.swing.JTextField txt_KullaniciProfilKullaniciAdi;
    private javax.swing.JTextField txt_KullaniciProfilMailAdresi;
    private javax.swing.JPasswordField txt_KullaniciProfilParola;
    private javax.swing.JTextField txt_KullaniciProfilSoyadi;
    private javax.swing.JFormattedTextField txt_KullaniciProfilTel;
    private javax.swing.JTextField txt_PersonelAdi;
    private javax.swing.JTextField txt_PersonelDepartmani;
    private javax.swing.JTextField txt_PersonelGorevi;
    private javax.swing.JButton txt_PersonelKaydet;
    private javax.swing.JTextField txt_PersonelKodu;
    private javax.swing.JTextField txt_PersonelMaili;
    private javax.swing.JTextField txt_PersonelSoyadi;
    private javax.swing.JButton txt_PersonelTemiz;
    private javax.swing.JTextField txt_UrunAdi;
    private javax.swing.JTextField txt_UrunAdiGuncelle;
    private javax.swing.JTextField txt_UrunKategori;
    private javax.swing.JTextField txt_UrunKategoriGuncelle;
    private javax.swing.JTextField txt_UrunKodu;
    private javax.swing.JTextField txt_UrunKoduGuncelle;
    // End of variables declaration//GEN-END:variables
}
