/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import bean.KayitOlanKullaniciBilgileri;
import dbislemleri.DatabaseIslemleri;
import java.text.ParseException;
import java.time.LocalDateTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import liste.Personel;
import model.Calisan;
import model.Kullanici;

/**
 *
 * @author mert tan
 */
public class KayitOl extends javax.swing.JFrame {
	
    private Login loginEkan;
        
    private DatabaseIslemleri db = new DatabaseIslemleri();
    /**
     * Creates new form KayıtOl
     */
    public KayitOl() throws ParseException {
        initComponents();
       
    }

    public void setLoginEkan(Login loginEkan) {
		this.loginEkan = loginEkan;
	}
    public Login getLoginEkan() {
		return loginEkan;
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_KayitOlAdi = new javax.swing.JTextField();
        txt_KayitOlSoyadi = new javax.swing.JTextField();
        txt_KayitOlKullaniciAdi = new javax.swing.JTextField();
        txt_KayitOlSifre = new javax.swing.JPasswordField();
        btn_KayitOl = new javax.swing.JButton();
        btn_KayitOlIptal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_KayitOlMailAdresi = new javax.swing.JTextField();
        txt_KayitOlTelefon = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YENİ KAYIT EKRANI");

        jLabel1.setText("ADI");

        jLabel2.setText("SOYADI");

        jLabel3.setText("KULLANICI ADI");

        jLabel4.setText("ŞİFRE");

        btn_KayitOl.setText("KAYIT OL");
        btn_KayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KayitOlActionPerformed(evt);
            }
        });

        btn_KayitOlIptal.setText("İPTAL");
        btn_KayitOlIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KayitOlIptalActionPerformed(evt);
            }
        });

        jLabel5.setText("MAIL ADRESI");

        jLabel6.setText("TEL");

        try {
            txt_KayitOlTelefon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_KayitOlIptal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_KayitOl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_KayitOlSoyadi)
                            .addComponent(txt_KayitOlKullaniciAdi)
                            .addComponent(txt_KayitOlSifre)
                            .addComponent(txt_KayitOlAdi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_KayitOlMailAdresi)
                            .addComponent(txt_KayitOlTelefon))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_KayitOlAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_KayitOlSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_KayitOlKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_KayitOlSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_KayitOlMailAdresi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_KayitOlTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_KayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_KayitOlIptal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_KayitOlIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KayitOlIptalActionPerformed

     Login loginsayfasi = new Login();
     loginsayfasi.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btn_KayitOlIptalActionPerformed
    
    private KayitOlanKullaniciBilgileri doldurKayitOlanKullaniciBilgilerini(){
        KayitOlanKullaniciBilgileri bilgiler = new KayitOlanKullaniciBilgileri();

        bilgiler.setAdi(txt_KayitOlAdi.getText().trim());
        bilgiler.setSoyadi(txt_KayitOlSoyadi.getText().trim());
        bilgiler.setKullaniciAdi(txt_KayitOlKullaniciAdi.getText().trim());
        bilgiler.setParola(String.copyValueOf(txt_KayitOlSifre.getPassword()));
        bilgiler.setMail(txt_KayitOlMailAdresi.getText().trim());
        bilgiler.setTelefonNumarasi(txt_KayitOlTelefon.getText().trim());
        bilgiler.setSistemeKayitTarihi(LocalDateTime.now());
                
        return bilgiler;
    }
    
    private boolean girilenBilgilerHatalimi(KayitOlanKullaniciBilgileri bilgiler){
        if(bilgiler.getAdi() == null || bilgiler.getAdi().equals("")){
            return false;
        }
        if(bilgiler.getSoyadi() == null || bilgiler.getSoyadi().equals("")){
            return false;
        }
        if(bilgiler.getMail() == null || bilgiler.getMail().equals("")){
            return false;
        }
        if(bilgiler.getKullaniciAdi()== null || bilgiler.getKullaniciAdi().equals("")){
            return false;
        }
        
        String regex = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(bilgiler.getMail());
        if(!matcher.matches()){
            return false;
        }
        return !(bilgiler.getParola()== null || bilgiler.getParola().isEmpty());    
    }
    
            
    private void btn_KayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KayitOlActionPerformed
        KayitOlanKullaniciBilgileri yeniKayitOlanKullanici = doldurKayitOlanKullaniciBilgilerini();
        boolean hataliGirisYapilmismi = girilenBilgilerHatalimi(yeniKayitOlanKullanici);
        if(hataliGirisYapilmismi == false) 
        {
            JOptionPane.showMessageDialog(rootPane, "HATALI BILGI GIRISI");
            return;
        }
        
        List<Kullanici> kayitlilKullanicilar = db.butunKayitliKullanicilariGetir();
        for(Kullanici mevcutKullanicilar:  kayitlilKullanicilar){
            if(mevcutKullanicilar.getKullaniciAdi().compareTo(yeniKayitOlanKullanici.getKullaniciAdi())== 0  &&
                    mevcutKullanicilar.getMail().compareTo(yeniKayitOlanKullanici.getMail()) == 0  &&
                    mevcutKullanicilar.getTelefonNumarasi().compareTo(yeniKayitOlanKullanici.getTelefonNumarasi())== 0 ){
                    
                    JOptionPane.showMessageDialog(rootPane, "KULLANICI ADI MEVCUT");
                    return;
            }
        }
        
        Kullanici yeniKullanici = kullaniciOlustur(yeniKayitOlanKullanici);
        db.kullaniciKaydet(yeniKullanici);
        
        kullaniciyiPersonelListesineEkle(yeniKayitOlanKullanici);
        
        JOptionPane.showMessageDialog(rootPane, "KAYIT BAŞARILI");
        this.getLoginEkan().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_KayitOlActionPerformed
    private Kullanici kullaniciOlustur(KayitOlanKullaniciBilgileri formKullaniciBilgileri){
        Kullanici kullanici = new Kullanici();
        kullanici.setAdi(formKullaniciBilgileri.getAdi());
        kullanici.setSoyadi(formKullaniciBilgileri.getSoyadi());
        kullanici.setKullaniciAdi(formKullaniciBilgileri.getKullaniciAdi());
        kullanici.setParola(new String(formKullaniciBilgileri.getParola()));
        kullanici.setMail(formKullaniciBilgileri.getMail());
        kullanici.setTelefonNumarasi(formKullaniciBilgileri.getTelefonNumarasi());
        kullanici.setSistemeKayitTarihi(LocalDateTime.now());
        return kullanici;
    }
    private void kullaniciyiPersonelListesineEkle(KayitOlanKullaniciBilgileri yeniKullanici){
        
        
        Personel personel = new Personel();
        personel.setKayitTarihi(yeniKullanici.getSistemeKayitTarihi());
        personel.setPersonelAdi(yeniKullanici.getAdi());
        personel.setPersonelMail(yeniKullanici.getMail());
        personel.setPersonelSoyadi(yeniKullanici.getSoyadi());
        
        
        List<Calisan> personeller = db.butunKayitliPersonelleriGetir();
        for(Calisan p : personeller){
            if(p.getPersonelMail().equals(personel.getPersonelMail())){
                JOptionPane.showMessageDialog(rootPane,"Sistemde personel mevcut");
                return ;
            }
        }
        
        Calisan calisan = calisanOlustur(personel);
        db.personelKaydet(calisan);
    }
    
    private Calisan calisanOlustur(Personel formPersonel){
        Calisan calisan = new Calisan();
        calisan.setKayitTarihi(LocalDateTime.now());
        calisan.setPersonelAdi(formPersonel.getPersonelAdi());
        calisan.setPersonelDepartmani(null); // yeni kayıtta departman secimi yapılmıyor kayit sonrasında menuden yapılır..
        calisan.setPersonelGorevi(formPersonel.getPersonelGorevi());
        calisan.setPersonelKodu(formPersonel.getPersonelKodu());
        calisan.setPersonelMail(formPersonel.getPersonelMail());
        calisan.setPersonelSoyadi(formPersonel.getPersonelSoyadi());
        
        return calisan;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KayitOl().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(KayitOl.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_KayitOl;
    private javax.swing.JButton btn_KayitOlIptal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_KayitOlAdi;
    private javax.swing.JTextField txt_KayitOlKullaniciAdi;
    private javax.swing.JTextField txt_KayitOlMailAdresi;
    private javax.swing.JPasswordField txt_KayitOlSifre;
    private javax.swing.JTextField txt_KayitOlSoyadi;
    private javax.swing.JFormattedTextField txt_KayitOlTelefon;
    // End of variables declaration//GEN-END:variables
}
