/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import anasayfa.Anasayfa;
import bean.KayitOlanKullaniciBilgileri;
import dbislemleri.DatabaseIslemleri;
import java.text.ParseException;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;
/**
 *
 * @author mert tan
 */
public class Login extends JFrame {
    
    
    DatabaseIslemleri db = new DatabaseIslemleri();

    /**
     * Creates new form Logın
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_kulalniciadi = new javax.swing.JTextField();
        txt_sifre = new javax.swing.JPasswordField();
        btn_giris = new javax.swing.JButton();
        btn_kayit_ol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGİN EKRANI");

        jLabel1.setText("KULLANICI ADI");

        jLabel2.setText("ŞİFRE");

        btn_giris.setText("GİRİŞ");
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });

        btn_kayit_ol.setText("KAYIT OL");
        btn_kayit_ol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayit_olActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_kayit_ol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_kulalniciadi)
                            .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txt_kulalniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_giris)
                    .addComponent(btn_kayit_ol))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayit_olActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayit_olActionPerformed
        try {
            kayitEkraniniAc();
        } catch (ParseException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_kayit_olActionPerformed
    private void kayitEkraniniAc() throws ParseException{
        KayitOl kayitOl = new KayitOl();
        kayitOl.setLoginEkan(this);
        kayitOl.setVisible(true);
        this.dispose();
    }
    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {                                          
       if(loginBilgileriKontrolEt()){
    	   KayitOlanKullaniciBilgileri girisYapanKullanici = loginOlanKullaniciKullanicilarListesindeVarmi();
    	   if(girisYapanKullanici!=null) {
    		   Anasayfa anasayfa = new Anasayfa(girisYapanKullanici,this);
    		   anasayfa.setVisible(true);
    		   this.dispose();
    	   }else{
                JOptionPane.showMessageDialog(rootPane,"Kullanıcı yok");
           }
       }else{
           JOptionPane.showMessageDialog(rootPane,"Giriş Bilgileri Eksik");
       }
    }
    private boolean loginBilgileriKontrolEt(){
        String kullaniciAdi=txt_kulalniciadi.getText().trim(); // trim bosluklari siler
        char[] parola = txt_sifre.getPassword();
        if(kullaniciAdi == null || kullaniciAdi.equals("")) return false;
        return parola.length >= 1;
    }
    private KayitOlanKullaniciBilgileri doldurLoginOlanKullaniciBilgileri() {
    	KayitOlanKullaniciBilgileri kullanici = new KayitOlanKullaniciBilgileri();
    	kullanici.setKullaniciAdi(txt_kulalniciadi.getText().trim());
    	kullanici.setParola(String.copyValueOf(txt_sifre.getPassword()));
    	return kullanici;
    }
    private KayitOlanKullaniciBilgileri loginOlanKullaniciKullanicilarListesindeVarmi() {
    	
    	KayitOlanKullaniciBilgileri girisYapanKullanici = doldurLoginOlanKullaniciBilgileri();
    	model.Kullanici kullanici = db.loginKullaniciVarmi(girisYapanKullanici.getKullaniciAdi(), girisYapanKullanici.getParola());
    	if(kullanici != null) return kayitOlanKullaniciBilgileriCevir(kullanici);
    	return null;
    }
    private KayitOlanKullaniciBilgileri kayitOlanKullaniciBilgileriCevir(model.Kullanici kullanici){
        KayitOlanKullaniciBilgileri kullaniciForm = new KayitOlanKullaniciBilgileri();
    	kullaniciForm.setKullaniciAdi(kullanici.getKullaniciAdi());
    	kullaniciForm.setParola(kullanici.getParola());
        kullaniciForm.setAdi(kullanici.getAdi());
        kullaniciForm.setSoyadi(kullanici.getSoyadi());
        kullaniciForm.setMail(kullanici.getMail());
        kullaniciForm.setTelefonNumarasi(kullanici.getTelefonNumarasi());
        kullaniciForm.setSistemeKayitTarihi(kullanici.getSistemeKayitTarihi());
        
        return kullaniciForm;
    }
            /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus l         aultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_giris;
    private javax.swing.JButton btn_kayit_ol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_kulalniciadi;
    private javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
